from apps.integrations.spotify.client import SpotifyClient
from apps.playlists.models import Playlist
from apps.playlists.models import PlaylistItem


class SpotifyExportService:
    """
    Export DB playlist → Spotify playlist
    """

    @staticmethod
    def export(playlist_id: int, access_token: str, name: str = None):
        client = SpotifyClient(access_token)
        local_playlist = Playlist.objects.get(id=playlist_id)

        # ----------------------------------------
        # 1. Fetch playlist items
        # ----------------------------------------
        items = PlaylistItem.objects.filter(
            playlist_id=playlist_id
        ).select_related("track").order_by("position")

        if not items.exists():
            raise ValueError("Playlist is empty")

        # ----------------------------------------
        # 2. Extract Spotify IDs
        # ----------------------------------------
        track_ids = []
        duplicate_count = 0
        missing_spotify_id_count = 0
        seen_track_ids = set()

        for item in items:
            spotify_id = item.track.spotify_id if item.track else None

            if not spotify_id:
                missing_spotify_id_count += 1
                continue

            if spotify_id in seen_track_ids:
                duplicate_count += 1
                continue

            seen_track_ids.add(spotify_id)
            track_ids.append(spotify_id)

        if not track_ids:
            raise ValueError("No Spotify tracks available")

        # ----------------------------------------
        # 3. Create Spotify playlist
        # ----------------------------------------
        playlist_name = (name or local_playlist.title or "Organized Playlist").strip()
        if not playlist_name:
            playlist_name = "Organized Playlist"

        spotify_playlist = client.create_playlist(
            name=playlist_name,
            description="Generated by MusicMixxer",
            public=False
        )

        spotify_playlist_id = spotify_playlist.get("id")
        local_playlist.spotify_id = spotify_playlist_id
        local_playlist.save(update_fields=["spotify_id", "updated_at"])

        # ----------------------------------------
        # 4. Add tracks
        # ----------------------------------------
        for chunk in SpotifyExportService._chunk_track_ids(track_ids):
            client.add_tracks_to_playlist(
                spotify_playlist_id,
                chunk
            )

        return {
            "spotify_playlist_id": spotify_playlist_id,
            "tracks_added": len(track_ids),
            "duplicates_skipped": duplicate_count,
            "tracks_skipped_without_spotify_id": missing_spotify_id_count,
        }

    @staticmethod
    def _chunk_track_ids(track_ids, chunk_size: int = 100):
        for index in range(0, len(track_ids), chunk_size):
            yield track_ids[index:index + chunk_size]
